version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - bridge-network

  nest: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn start
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - bridge-network

volumes:
  mongodb_data_container:

networks:
  bridge-network:
    driver: bridge